
const actionTypes = {
    LOGIN_PROGRESS : 'LOGIN_PROGRESS',
    LOGIN_SUCCEED : 'LOGIN_SUCCEED',
    SIGNUP_PROGRESS : 'SIGNUP_PROGRESS',
    SIGNUP_SUCCEED : 'SIGNUP_SUCCEED',
    LOGOUT_SUCCEED : 'LOGOUT_SUCCEED',
    LOGIN_ERROR: 'LOGIN_ERROR',
    SIGNUP_ERROR : 'SIGNUP_ERROR',
    SIGNUP_ERROR_ALERT : 'SIGNUP_ERROR_ALERT',
    LOGIN_ERROR_ALERT : 'LOGIN_ERROR_ALERT',

    STATUS:'STATUS',

    CREATE_PROFILE: 'CREATE_PROFILE',

    LOAD_USER_PROFILE: 'LOAD_USER_PROFILE',

    LOAD_ALL_STUDENTS: 'LOAD_ALL_STUDENTS',

    LOAD_VACANCY: 'LOAD_VACANCY',

    LOAD_ALL_COMPANIES: 'LOAD_ALL_COMPANIES',

    LOAD_ALL_STUDENTS_REQUEST: 'LOAD_ALL_STUDENTS_REQUEST',

    REMOVE_VACANCY : 'REMOVE_VACANCY',

    CLEAR_USER_PROFILE: 'CLEAR_USER_PROFILE',

    LOAD_COMPANY_REQUEST: 'LOAD_COMPANY_REQUEST',

    REMOVE_STUDENT: 'REMOVE_STUDENT',

}
export default actionTypes;